#!/bin/sh
# Because I don't hate myself enough.  Licensed under BSD 2 Clause
# License.

#  Numbers are represented as xxxx.yyyyyy
# If you have more than one dot in the string, you're fucked.

# Return N question marks.
__nqnmarks(){
	x=
	n=0
	while [ $n -lt $1 ]; do
		x="$x?"
		: $((n+=1))
	done
	echo "$x"
	unset x n
}

# Return 10eN.
__tenpower(){
	case $1 in
	0) echo 1 ;;
	1) echo 10 ;;
	2) echo 100 ;;
	3) echo 1000 ;;
	4) echo 10000 ;;
	5) echo 100000 ;;
	*)
		x=100000
		n=5
		while [ $n -lt $1 ]; do
			x="${x}0"
			: $((n+=1))
		done
		echo "$x"
		unset x n
	esac
}

# Add $1 and $2.
add(){
	float1="${1#*.}"
	dec1="${1%%."${float1}"}"
	float2="${2#*.}"
	dec2="${2%%."${float2}"}"
	nfloat1=${#float1}
	nfloat2=${#float2}

	: $((maxf = nfloat1 >= nfloat2 ? nfloat1 : nfloat2))

	: $((newf = (float1 * $(__tenpower $((maxf - nfloat1))))
		 + (float2 * $(__tenpower $((maxf - nfloat))))))

	: $((tenmaxf = $(__tenpower $maxf)))

	: $((extradec = newf / tenmaxf))

	echo $((dec1 + dec2 + extradec)).$((newf - (extradec * tenmaxf)))

	unset dec1 float1 dec2 float2 maxf newf tenmaxf extradec
}
