#!/bin/sh -x

. ./mathsh

assert(){
	[ "$1" = "$2" ] && echo "yes" || echo "no"
}

x=10
y=20
echo $(($x$y * 10))

echo $((x ^ 2))

assert $(__tenpower 4) 10000
assert $(__tenpower 8) 100000000
assert $(__tenpower 16) 10000000000000000

assert $((1 > 2 ? 1 : 2)) 2
: $((x=4 / 2)); echo $x

echo $(__padzero 5 2)

assert $(add 1.2 2.9) 4.1

assert $(add 2.123 4.523) 6.646

assert $(add 139.1231239485 12.234)	151.3571239485

assert $(sub 1.2 3.1) -1.9

assert $(sub 1.0 -1.0) 2.0

assert $(sub 1.0 1.0) 0.0

assert $(add 1.0 -1.0) 0.0

assert $(add 0.4 0.6) 1.0

assert $(mult 0.5 0.1) 0.05

assert $(mult 0.1 -0.5) -0.05

assert $(sub 0.001 0.1235) -0.1225
